stages:
  - testing

Integration test:
  image: node:10.11.0-alpine
  services:
    - docker:stable
  stage: testing
  before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

  script:
    - echo "testing"
    - npm --version
    - node --version
    - yarn --version
    - docker-compose --version