stages:
  - testing

End-to-end testing:
  image: node:10.11.0-alpine
  stage: testing
  before_script:
  #  - apk add chromium
  script:
    - yarn
    - ls -la node_modules/chromedriver/lib/chromedriver/chromedriver
    - whereis chromedriver
    # - yarn && yarn test:prod