stages:
  - testing

Integration test:
  image: docker:stable
  services:
    - node:10.11.0-alpine
    - docker:dind
  stage: testing
  before_script:
  - apk add --update py-pip && pip install docker-compose
  - npm install -g prisma
  script:
    - echo "testing"
    - npm --version
    - node --version
    - yarn --version
    - docker-compose --version
    - prisma --version