stages:
  - testing

Integration test:
  image: node:10.11.0-alpine
  services:
    - docker:dind
  stage: testing
  only:
    - /^sprint\d+$/
  except:
    - schedules
  script:
    - echo "testing"
    - npm --version
    - node --version
    - yarn --version
    - docker --version
    - docker-compose --version