stages:
  - testing

Integration test:
  image: node:10.11.0-alpine
  services:
    - docker:stable
  stage: testing
  script:
    - echo "testing"
    - npm --version
    - node --version
    - yarn --version
    - docker-compose --version