stages:
  - build

job 1:
  image: docker:stable
  services:
    - docker:dind

  stage: build
  
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

  script:
    - echo $CONTAINER_TEST_IMAGE
    - echo $CONTAINER_RELEASE_IMAGE